apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restapi-flask
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  project: application
  source:
    repoURL: <YOUR_GIT_REPO_URL>  # Ex: https://github.com/seu-usuario/helm-applications.git
    path: restapi-flask
    targetRevision: main
    helm:
      releaseName: flask
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: api